export const LOGIN_TEACHER = "LOGIN_TEACHER";
export const LOADING_ACTIVE = "LODING_ACTIVE";
export const LOADING_DONE = "LODING_DONE";
export const NOTICE_FETCH = "NOTICE_FETCH";
export const NOTICE_ADD = "NOTICE_ADD";
export const CLASS_FETCH = "CLASS_FETCH";
export const EXAM_FETCH = "EXAM_FETCH";
export const EXAM_ADD = "EXAM_ADD";
export const SUBJECT_FETCH = "SUBJECT_FETCH";



// export const TEACHER_FETCH = "TEACHER_FETCH";
// export const TEACHER_SUBJECT_FETCH = "TEACHER_SUBJECT_FETCH";
// export const TEACHER_CLASS_FETCH = "TEACHER_CLASS";
// export const CLASS_SUBJECT_FETCH = "CLASS_SUBJECT_FETCH";
// export const CLASS_MATERIAL_ADD = "CLASS_MATERIAL_ADD";
// export const ATTEDANCE_ADD = "ATTEDANCE_ADD";
// export const FETCH_CLASS_STUDENT = "FETCH_CLASS_STUDENT";